import { NarrativeSchema } from '../types/narrative';

export const irbNarrativeSchema: NarrativeSchema = {
  sections: [
    // Module 1: Study Foundation & Context
    {
      id: 'studyRationale',
      title: 'Study Rationale',
      moduleId: 'foundation',
      moduleName: 'Study Foundation & Context',
      description: 'Help us understand why this research is necessary and what gap it fills.',
      template: 'This research project aims to address {researchGap} in the field of AI/ML healthcare applications. Based on {literatureRefs}, there is a clear need to explore new methods for {researchObjective}. Our project will specifically focus on {methodologyApproach}, which has shown promise in {priorEvidence}.',
      fields: [
        {
          id: 'researchGap',
          type: 'textArea',
          label: 'Research Gap',
          placeholder: 'What specific gap in current knowledge does your project address?',
          validation: [{ type: 'required', message: 'Research gap description is required' }],
          helpText: 'Describe the current limitation or gap in knowledge that your project will address',
        },
        {
          id: 'literatureRefs',
          type: 'textArea',
          label: 'Supporting Literature',
          placeholder: 'What published literature supports your approach?',
          validation: [{ type: 'required', message: 'Supporting literature is required' }],
          helpText: 'Include key citations that support your methods and demonstrate the gap',
        },
        {
          id: 'researchObjective',
          type: 'textArea',
          label: 'Research Objective',
          placeholder: 'What specific objective will your project pursue?',
          validation: [{ type: 'required', message: 'Research objective is required' }],
        },
        {
          id: 'methodologyApproach',
          type: 'textArea',
          label: 'Methodology Approach',
          placeholder: 'Describe your planned approach',
          validation: [{ type: 'required', message: 'Methodology approach is required' }],
        },
        {
          id: 'priorEvidence',
          type: 'textArea',
          label: 'Prior Evidence',
          placeholder: 'What evidence suggests this approach will be successful?',
          validation: [{ type: 'required', message: 'Prior evidence is required' }],
        },
      ],
    },
    {
      id: 'studyPopulation',
      title: 'Study Population',
      moduleId: 'foundation',
      moduleName: 'Study Foundation & Context',
      description: 'Define who you will be studying and why.',
      template: 'Our study will focus on patients with {diagnosis}. {includeHealthyControls, select, yes: We will include healthy controls for comparison purposes. {healthyControlJustification} | no: We will not include healthy controls in this study.} The study population will include individuals aged {minAge} to {maxAge} years.',
      fields: [
        {
          id: 'diagnosis',
          type: 'text',
          label: 'Primary Diagnosis/Condition',
          placeholder: 'What is the main condition you are studying?',
          validation: [{ type: 'required', message: 'Primary diagnosis is required' }],
        },
        {
          id: 'includeHealthyControls',
          type: 'radio',
          label: 'Include Healthy Controls?',
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          validation: [{ type: 'required', message: 'Please specify if healthy controls will be included' }],
        },
        {
          id: 'healthyControlJustification',
          type: 'textArea',
          label: 'Healthy Control Justification',
          placeholder: 'Why are healthy controls necessary for your study?',
          dependsOn: { fieldId: 'includeHealthyControls', value: 'yes' },
        },
        {
          id: 'minAge',
          type: 'number',
          label: 'Minimum Age',
          validation: [
            { type: 'required', message: 'Minimum age is required' },
            { type: 'min', value: 0, message: 'Age must be 0 or greater' },
          ],
        },
        {
          id: 'maxAge',
          type: 'number',
          label: 'Maximum Age',
          validation: [
            { type: 'required', message: 'Maximum age is required' },
            { type: 'min', value: 0, message: 'Age must be 0 or greater' },
          ],
        },
      ],
    },

    // Module 2: Data & Resources
    {
      id: 'dataAccess',
      title: 'Data Access & Resources',
      moduleId: 'data',
      moduleName: 'Data & Resources',
      description: 'Specify what resources you need and who will have access.',
      template: 'This study will utilize the following resources: {resourceTypes}. {otherIrbData, select, yes: This includes data from IRB #{otherIrbNumber}. | no: } Access to the study data will be provided to {mayoAccess} within Mayo Clinic and {nonMayoAccess} outside Mayo Clinic.',
      fields: [
        {
          id: 'resourceTypes',
          type: 'multiSelect',
          label: 'Required Resources',
          options: [
            { value: 'data', label: 'Data (e.g., EHR data)' },
            { value: 'video_audio', label: 'Video/Audio Recordings' },
            { value: 'specimens', label: 'Specimens' },
            { value: 'images', label: 'Images' },
            { value: 'medical_records', label: 'Medical Records' },
          ],
          validation: [{ type: 'required', message: 'At least one resource type is required' }],
        },
        {
          id: 'otherIrbData',
          type: 'radio',
          label: 'Using Data from Another IRB?',
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
        },
        {
          id: 'otherIrbNumber',
          type: 'text',
          label: 'Other IRB Number',
          dependsOn: { fieldId: 'otherIrbData', value: 'yes' },
        },
        {
          id: 'mayoAccess',
          type: 'textArea',
          label: 'Mayo Clinic Access',
          placeholder: 'Who within Mayo Clinic will have access to the study data?',
          validation: [{ type: 'required', message: 'Mayo access details are required' }],
        },
        {
          id: 'nonMayoAccess',
          type: 'textArea',
          label: 'Non-Mayo Access',
          placeholder: 'Who outside Mayo Clinic will have access to the study data?',
          validation: [{ type: 'required', message: 'Non-Mayo access details are required' }],
        },
      ],
    },
    {
      id: 'dataTimeframe',
      title: 'Data Collection Timeframe',
      moduleId: 'data',
      moduleName: 'Data & Resources',
      description: 'Define when the data was or will be collected.',
      template: 'The data used in this study was collected between {startDate} and {endDate} for baseline analysis{hasFollowup, select, yes:, with follow-up data through {followupDate} | no:}.',
      fields: [
        {
          id: 'startDate',
          type: 'date',
          label: 'Start Date',
          validation: [{ type: 'required', message: 'Start date is required' }],
        },
        {
          id: 'endDate',
          type: 'date',
          label: 'End Date',
          validation: [{ type: 'required', message: 'End date is required' }],
        },
        {
          id: 'hasFollowup',
          type: 'radio',
          label: 'Include Follow-up Data?',
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
        },
        {
          id: 'followupDate',
          type: 'date',
          label: 'Follow-up End Date',
          dependsOn: { fieldId: 'hasFollowup', value: 'yes' },
        },
      ],
    },
    {
      id: 'sampleSize',
      title: 'Sample Size Requirements',
      moduleId: 'data',
      moduleName: 'Data & Resources',
      description: 'Specify how many records you need and why.',
      template: 'To draw meaningful conclusions, we require {totalRecords} total records, with {mayoRecords} sourced from Mayo Clinic. This sample size was determined based on {powerJustification}.',
      fields: [
        {
          id: 'totalRecords',
          type: 'number',
          label: 'Total Records Needed',
          validation: [
            { type: 'required', message: 'Total number of records is required' },
            { type: 'min', value: 1, message: 'Must be greater than 0' },
          ],
        },
        {
          id: 'mayoRecords',
          type: 'number',
          label: 'Mayo Clinic Records',
          validation: [
            { type: 'required', message: 'Number of Mayo records is required' },
            { type: 'min', value: 0, message: 'Cannot be negative' },
          ],
        },
        {
          id: 'powerJustification',
          type: 'textArea',
          label: 'Statistical Power Justification',
          placeholder: 'Explain how you determined the required sample size',
          validation: [{ type: 'required', message: 'Power justification is required' }],
        },
      ],
    },

    // Module 3: Privacy & Compliance
    {
      id: 'dataPrivacy',
      title: 'Data Privacy & Security',
      moduleId: 'privacy',
      moduleName: 'Privacy & Compliance',
      description: 'Specify how data privacy and security will be maintained.',
      template: 'The data used in this study will be {identifiabilityLevel}. {identifiabilityDetails} Data will be securely stored in {storageLocation} and transferred using {transferMethod}.',
      fields: [
        {
          id: 'identifiabilityLevel',
          type: 'select',
          label: 'Data Identifiability Level',
          options: [
            { value: 'synthetic', label: 'Synthetic dataset' },
            { value: 'deidentified', label: 'Deidentified per HIPAA standards' },
            { value: 'limited', label: 'Limited dataset' },
            { value: 'coded', label: 'Coded with key/crosswalk' },
            { value: 'identifiable', label: 'Fully identifiable' },
          ],
          validation: [{ type: 'required', message: 'Identifiability level is required' }],
        },
        {
          id: 'identifiabilityDetails',
          type: 'textArea',
          label: 'Identifiability Details',
          placeholder: 'Provide details about data identifiability and protection measures',
          validation: [{ type: 'required', message: 'Identifiability details are required' }],
        },
        {
          id: 'storageLocation',
          type: 'text',
          label: 'Storage Location',
          placeholder: 'Where will the data be stored?',
          validation: [{ type: 'required', message: 'Storage location is required' }],
        },
        {
          id: 'transferMethod',
          type: 'text',
          label: 'Transfer Method',
          placeholder: 'How will data be securely transferred?',
          validation: [{ type: 'required', message: 'Transfer method is required' }],
        },
      ],
    },
    {
      id: 'sensitiveData',
      title: 'Sensitive Data Handling',
      moduleId: 'privacy',
      moduleName: 'Privacy & Compliance',
      description: 'Identify any sensitive data and its protection measures.',
      template: '{hasSensitiveData, select, yes: This study includes sensitive data types: {sensitiveDataTypes}. {sensitiveDataProtections} | no: This study does not include any sensitive data types.}',
      fields: [
        {
          id: 'hasSensitiveData',
          type: 'radio',
          label: 'Does this study include sensitive data?',
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          validation: [{ type: 'required', message: 'Please indicate if sensitive data is included' }],
        },
        {
          id: 'sensitiveDataTypes',
          type: 'multiSelect',
          label: 'Sensitive Data Types',
          options: [
            { value: 'psychiatric', label: 'Psychiatric Information' },
            { value: 'substance', label: 'Substance Use' },
            { value: 'hiv', label: 'HIV Status' },
            { value: 'genetic', label: 'Genetic Information' },
            { value: 'abuse', label: 'Abuse History' },
            { value: 'other', label: 'Other Sensitive Information' },
          ],
          dependsOn: { fieldId: 'hasSensitiveData', value: 'yes' },
        },
        {
          id: 'sensitiveDataProtections',
          type: 'textArea',
          label: 'Protection Measures',
          placeholder: 'Describe additional protections for sensitive data',
          dependsOn: { fieldId: 'hasSensitiveData', value: 'yes' },
        },
      ],
    },
    {
      id: 'vendorPrivacy',
      title: 'Third-Party & Vendor Privacy',
      moduleId: 'privacy',
      moduleName: 'Privacy & Compliance',
      description: 'Specify how privacy will be maintained with external tools or vendors.',
      template: '{usesExternalTools, select, yes: This study will utilize external tools/vendors: {externalTools}. Privacy will be maintained through {privacyMeasures}. | no: This study will not utilize any external tools or vendors.}',
      fields: [
        {
          id: 'usesExternalTools',
          type: 'radio',
          label: 'Will you use external tools or vendors?',
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          validation: [{ type: 'required', message: 'Please specify if external tools will be used' }],
        },
        {
          id: 'externalTools',
          type: 'textArea',
          label: 'External Tools/Vendors',
          placeholder: 'List the external tools or vendors you will use',
          dependsOn: { fieldId: 'usesExternalTools', value: 'yes' },
        },
        {
          id: 'privacyMeasures',
          type: 'textArea',
          label: 'Privacy Measures',
          placeholder: 'Describe how privacy will be maintained with external tools',
          dependsOn: { fieldId: 'usesExternalTools', value: 'yes' },
        },
      ],
    },

    // Module 4: Impact & Future Considerations
    {
      id: 'fairnessAndImpact',
      title: 'Fairness & Impact Assessment',
      moduleId: 'impact',
      moduleName: 'Impact & Future Considerations',
      description: 'Evaluate the fairness and impact of your research.',
      template: 'This research will benefit {beneficiaries} through {benefits}. The findings will impact the source populations by {populationImpact}. To ensure algorithmic fairness, we will implement {fairnessMeasures}.',
      fields: [
        {
          id: 'beneficiaries',
          type: 'textArea',
          label: 'Who will benefit?',
          placeholder: 'Describe who will directly benefit from this technology',
          validation: [{ type: 'required', message: 'Beneficiaries must be specified' }],
        },
        {
          id: 'benefits',
          type: 'textArea',
          label: 'Expected Benefits',
          placeholder: 'Describe the expected benefits',
          validation: [{ type: 'required', message: 'Benefits must be specified' }],
        },
        {
          id: 'populationImpact',
          type: 'textArea',
          label: 'Population Impact',
          placeholder: 'How will findings benefit source populations?',
          validation: [{ type: 'required', message: 'Population impact must be specified' }],
        },
        {
          id: 'fairnessMeasures',
          type: 'textArea',
          label: 'Fairness Measures',
          placeholder: 'How will you ensure algorithmic fairness?',
          validation: [{ type: 'required', message: 'Fairness measures must be specified' }],
        },
      ],
    },
    {
      id: 'futureUse',
      title: 'Future Use & Limitations',
      moduleId: 'impact',
      moduleName: 'Impact & Future Considerations',
      description: 'Specify future plans and current limitations.',
      template: '{plansFutureUse, select, yes: We plan to use this study\'s data for future research: {futureUseDetails} | no: We do not plan to use this study\'s data for future research.} This study adheres to Phase 1 limitations: {phase1Compliance}.',
      fields: [
        {
          id: 'plansFutureUse',
          type: 'radio',
          label: 'Plans for Future Use',
          options: [
            { value: 'yes', label: 'Yes' },
            { value: 'no', label: 'No' },
          ],
          validation: [{ type: 'required', message: 'Future use plans must be specified' }],
        },
        {
          id: 'futureUseDetails',
          type: 'textArea',
          label: 'Future Use Details',
          placeholder: 'Describe planned future uses',
          dependsOn: { fieldId: 'plansFutureUse', value: 'yes' },
        },
        {
          id: 'phase1Compliance',
          type: 'multiSelect',
          label: 'Phase 1 Compliance',
          options: [
            { value: 'records_only', label: 'Limited to records review' },
            { value: 'no_epic', label: 'No live medical environment integration' },
            { value: 'no_deployment', label: 'No algorithm deployment' },
            { value: 'no_provider_exposure', label: 'No provider exposure to output' },
            { value: 'ideation_only', label: 'Limited to ideation phase' },
          ],
          validation: [{ type: 'required', message: 'Phase 1 compliance must be specified' }],
        },
      ],
    },
  ],
  metadata: {
    version: '2.0.0',
    lastUpdated: new Date().toISOString(),
    institution: 'Mayo Clinic',
    type: 'AI/ML',
  },
}; 